### ISSUE TITLE
Could not find a version that satisfies the requirement printnodeapi

### ISSUE THREAD

**Issue by kylerwinters** [mxmo-co/printnode-integration#6]
Could not find a version that satisfies the requirement printnodeapi (from printnode-integration==0.0.1) (from versions: )
No matching distribution found for printnodeapi (from printnode-integration==0.0.1)

**Comment by MaxMorais** [comment]
@kylerwinters 

install print node using

```
./env/bin/pip install -e git+https://github.com/PrintNode/PrintNode-Python#egg=printnodeapi
```

Frappe dont handle properly the requirements for that condition

**Comment by MaxMorais** [comment]
It will be closed due inactivity
